name: CI Checks
on: 
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 2
      - name: Use Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run lint
      - run: npm run format:check
